Repository FlatbreadLabs/flatbread, pull requests merged in 2022-07, with the labels that each got.

#23 Add badges & Slack link to docs
  README.md
  packages/flatbread/README.md
Labels: documentation

#22 Bounded GraphQL server cache
  package.json
  packages/flatbread/package.json
  packages/flatbread/src/cli/index.ts
  packages/flatbread/src/graphql/server.ts
  pnpm-lock.yaml
Labels: enhancement

#25 recursive directory scan for source-filesystem
  package.json
  packages/source-filesystem/README.md
  packages/source-filesystem/src/index.ts
  packages/source-filesystem/src/types.ts
  packages/source-filesystem/src/utils/gatherFileNodes.ts
  packages/source-filesystem/src/utils/tests/gatherFileNodes.test.ts
  packages/source-filesystem/src/utils/tests/mocks.ts
  packages/source-filesystem/src/utils/tests/snapshots/gatherFileNodes.test.ts.md
  packages/source-filesystem/src/utils/tests/snapshots/gatherFileNodes.test.ts.snap
  packages/transformer-markdown/src/index.ts
  packages/transformer-yaml/src/index.ts
  playground/content/markdown/posts/art/test.md
  playground/content/markdown/posts/category with space/test.md
  playground/content/markdown/posts/code/another-category-test.md
  playground/flatbread.config.js
  playground/src/routes/index.svelte
Labels: transformers, source-filesystem, config

#31 allow serverside function flatbread
  ava.config.js
  package.json
  packages/core/src/generators/schema.ts
  packages/core/src/index.ts
  packages/core/src/providers/base.ts
  packages/core/src/providers/test/base.test.ts
  packages/core/src/providers/test/snapshots/base.test.ts.md
  packages/core/src/providers/test/snapshots/base.test.ts.snap
  packages/core/src/types.ts
  packages/core/src/utils/deepEntries.ts
  packages/core/src/utils/sift.ts
  packages/core/src/utils/tests/sift.test.ts
  packages/core/src/utils/tests/typeOf.test.ts
  packages/flatbread/src/graphql/server.ts
  packages/source-filesystem/src/utils/tests/gatherFileNodes.test.ts
  pnpm-lock.yaml
Labels: enhancement

#29 field overrides first pass
  README.md
  packages/core/src/generators/schema.ts
  packages/core/src/types.ts
  packages/core/src/utils/fieldOverrides.ts
  packages/core/src/utils/tests/fieldOverrides.test.ts
  packages/core/src/utils/tests/snapshots/fieldOverrides.test.ts.md
  packages/core/src/utils/tests/snapshots/fieldOverrides.test.ts.snap
  playground/content/markdown/deeply-nested/test.md
  playground/flatbread.config.js
  pnpm-lock.yaml
Labels: enhancement, gql-schema, config, core

#30 allow multiple transformers
  packages/config/src/index.ts
  packages/core/src/generators/schema.ts
  packages/core/src/index.ts
  packages/core/src/providers/base.ts
  packages/core/src/types.ts
  packages/core/src/utils/initializeConfig.ts
  packages/flatbread/package.json
  packages/flatbread/src/index.ts
  packages/flatbread/src/utils/getSchema.ts
  packages/source-filesystem/package.json
  packages/source-filesystem/src/index.ts
  packages/source-filesystem/src/types.ts
  packages/transformer-markdown/src/index.ts
  packages/transformer-markdown/src/types.ts
  packages/transformer-yaml/README.md
  packages/transformer-yaml/src/index.ts
  packages/transformer-yaml/src/tests/index.test.ts
  packages/transformer-yaml/src/tests/index.test.ts.md
  packages/transformer-yaml/src/tests/index.test.ts.snap
  packages/transformer-yaml/src/tests/snapshots/index.test.ts.md
  packages/transformer-yaml/src/tests/snapshots/index.test.ts.snap
  playground/flatbread.config.js
  pnpm-lock.yaml
Labels: transformers, source-filesystem, config, core

#68 Run the pipeline on external PRs
  .github/workflows/pipeline.yml
Labels: CI / CD
